Sprint a
KenzieAcademy/backend-epithet-generator pull request #3
Opened 2018-10-16 16:00 UTC by maparsons83

Submission for sprint A.  All requirements listed in README fulfilled.

2018-10-17 21:01 UTC, infosmith requested changes
None of your files have docstrings or a shebang.

2018-10-17 21:01 UTC, infosmith commented on submissions/sprint_a/__init__.py
> +    PROJECT_ROOT = os.path.dirname('.')
use os.path.dirname(os.path.abspath(\_\_file__)) instead of os.path.dirname('.'). It's safer.

2018-10-17 21:01 UTC, infosmith commented on submissions/sprint_a/app.py
> +from sprint_a import app
Check the ordering of your imports: https://www.python.org/dev/peps/pep-0008/#imports
Imports should be grouped in the following order:
Standard library imports.
Related third party imports.
Local application/library specific imports.
You should put a blank line between each group of imports.

2018-11-01 20:32 UTC, itsthejoker commented
👍

2018-11-01 20:32 UTC, closed without merging