Sprint a
KenzieAcademy/backend-epithet-generator pull request #4
Opened 2018-10-16 18:49 UTC by jakeberg

2018-10-17 21:15 UTC, infosmith requested changes
Please add docstrings to all of your files.

2018-10-17 21:15 UTC, infosmith commented on submissions/sprint_a/Pipfile
> +python_version = "2.7"
Flask supports python 2.7 and >= 3.4. I recommend using 3.6 and above.
http://flask.pocoo.org/docs/1.0/installation/

2018-10-17 21:15 UTC, infosmith commented on submissions/sprint_a/__init__.py
> +    load_dotenv(dotenv_path=env_path, verbose=True, override=True)
use os.path.dirname(os.path.abspath(\_\_file__)) instead. It's safer.

2018-10-17 21:15 UTC, infosmith commented on submissions/sprint_a/__init__.py
> +    from flask import Flask, jsonify
You don't need to import jsonify here. It's a flask module but not part of flask configuration. You import jsonify anywhere in an app and it's fine.

2018-10-17 21:15 UTC, infosmith commented on submissions/sprint_a/__init__.py
> +    return app, jsonify
limit your returns to instances of app, db, etc...

2018-10-17 21:15 UTC, infosmith commented on submissions/sprint_a/app.py
> +
On functions this small, docstrings really aren't necessary, but a docstring or remove the newline.

2018-10-17 21:15 UTC, infosmith commented on submissions/sprint_a/app.py
> +    return jsonify(response)
You can save yourself a variable assignment and just return the dictionary using jsonify.

2018-11-01 20:27 UTC, itsthejoker commented
Finally graded!

2018-11-01 20:27 UTC, closed without merging