Sprint a
KenzieAcademy/backend-epithet-generator pull request #5
Opened 2018-10-16 18:52 UTC by ptrthegr8

2018-10-17 21:38 UTC, infosmith requested changes
Please add docstrings and a shebang to your files.

2018-10-17 21:38 UTC, infosmith commented on submissions/sprint_a/__init__.py
> +    PROJECT_ROOT = os.path.dirname('.')
use os.path.dirname(os.path.abspath(\_\_file__)), is safer

2018-10-17 21:38 UTC, infosmith commented on submissions/sprint_a/app.py
> +from flask import jsonify
Check the order of your imports: https://www.python.org/dev/peps/pep-0008/#imports

Imports should be grouped in the following order:
Standard library imports.
Related third party imports.
Local application/library specific imports.
You should put a blank line between each group of imports.

2018-11-01 20:31 UTC, itsthejoker commented
:+1:

2018-11-01 20:31 UTC, closed without merging